config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/photos',  to: 'static_pages#photos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'will_paginate/array'

  def home
  end

  def photos
    @person = Flickr.people.find(params[:search][:id])
    @photos =  Flickr.photos.search(user_id: @person.id, page: params[:page], per_page: 21)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to "FIND" ,root_path %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-container">
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="info-box">
  <h4>Search Flickr's User Photos!</h4>
</div>
<div class="row">
  <div class="col-centered">
    <div class="form">
      <%= form_for(:search, url: photos_path, method: :get) do |f| %>
        <%= f.text_field :id, class: 'form-field', label: "id" %>
        <%= f.submit "Search User Photos By ID", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/photos.html.erb
<div class="large"  style="width:100%;">
  <div class="row">
      <% @photos.each do |photo| %>
        <div class="image">
          <a href="<%= photo.medium500.source_url %>">
          <%= image_tag photo.square150.source_url %>
        </div> 
      <% end %>
  </div>
  <div class="pagination">
    <%= will_paginate @photos %>
  </div>
</div>